spring:
  datasource:
    url: jdbc:postgresql://db:5432/demo_db
    username: demo_user
    password: demo_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

clickhouse:
  url: jdbc:clickhouse://clickhouse:8123/default?compress=1
  username: ch_user
  password: clickhouse_pass